/*Each new term in the Fibonacci sequence is generated by adding the previous 
two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed 
four million, find the sum of the even-valued terms. */

#include <stdio.h>
#include <stdlib.h>

int main(){
  int one = 1;
  int two = 2;
  int three = one + two;
  int ret = two;
  while (three < 4000000){
    if (three % 2 == 0){
      ret += three;
    }
    one = two;
    two = three;
    three = one + two;
  }
  printf("%d\n", ret);
  return 0;

}
